const express = require('express')
const router = express.Router()
const TutorAndStudent = require('../Apps/Controllers/StudentAndTutor.controller')

router.route('/')
    .get(TutorAndStudent.Index_Page)
router.route('/profile')
    .get(TutorAndStudent.Profile_Page)
router.route('/:faculty_id/Subject')
    .get(TutorAndStudent.Subject_Page)
router.route('/:faculty_id/Subject/:subject_id/:user_id/Class')
    .get(TutorAndStudent.Class_Page)
router.route('/:faculty_id/Subject/:subject_id/Class/:class_id')
    .get(TutorAndStudent.Detail_Class)
module.exports = router